### ISSUE TITLE
Platform requirements for running Chillin

### ISSUE THREAD

**Issue by ola-andersson** [ChalmersLibrary/Chillin#8]
Please state what are the hardware/software platform requirements for running Chillin.

**Comment by larkov** [comment]
We are developing on Umbraco 6.xx at the moment so the requirements on https://our.umbraco.org/documentation/Installation/system-requirements are applicable for our project as well. As for hardware we run it on a Standard Azure Web App on a small instance (1 core, 1.75GB memory).
